### PR TITLE
Revamp screen shots for release v2.10.2

### LINKED ISSUE #11: New screenshot of nearby places with icons
As soon as the icons are implemented the screenshot of the nearby-places screen should be replaced.

### PR DESCRIPTION
**Pull request by sivaraam**
Fixes #11.

Some images are kept without being used just in case they are needed in
future.

## Notes
This is my first attempt at trying to revamp the screen shots. Let me know if they are OK. They could be seen live at https://sivaraam.github.io/commons-app.github.io/

Question: Can the explore feature be used just to discover images? Or can it be used to discover other kind of media such as audio, video etc.? I was only able to see images in Explore for my searches.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Looks great!
I would just change the wording of the title/description image to something much more specific, for instance:

Title: Woman working in rice field in Khoria, Uttar Pradesh
Description: Picture taken between drainage and harvest. The woman wears a blue and pink dress typical of Khoria

... or something similar, because I just made that up.
This is important, to show users they should enter very meaningful and precise information :-)

**Comment by sivaraam** [comment]
I've made the change you have suggested @nicolas-raoul.

Also, I've made some other fixes. Please review and let me know if we could merge this. It would be nice if you could also take a look at #37 which is a minor improvement. Merging it would make the sites text font more appealing, IMO.

**Comment by domdomegg** [comment]
Some more feedback (sorry for not providing earlier):
- Use the default Android font (Roboto) instead of what I believe is Rosemary. I think it looks cleaner and more professional for the site. This is just my own personal view and is probably a matter of style up for debate though, so feel free to ignore if you prefer :)
- Investigate why the app bar text seems to have a load of padding to the left. In the search activity this is extreme, 'flowers' is practically centred! This is probably a bug, would be good to open an issue if so.
- Ensure all the photographs in the screenshots are licensed properly (e.g. the woman working in the paddy fields, and the ones in explore might have attribution requirements)

**Comment by sivaraam** [comment]
> Some more feedback (sorry for not providing earlier):
> 
>     * Use the default Android font (Roboto) instead of what I believe is Rosemary. I think it looks cleaner and more professional for the site. This is just my own personal view and is probably a matter of style up for debate though, so feel free to ignore if you prefer :)
> 

That's a good point :slightly_smiling_face:  I actually noted that I've forgot to switch fonts only after taking the screen shots and was lazy to take them again and left it unchanged for someone to point out. Since you've pointed it out, I've changed the screen shots. As a bonus, it was also possible to feature the ongoing campaigns :wink: 


>     * Investigate why the app bar text seems to have a load of padding to the left. In the search activity this is extreme, 'flowers' is practically centred! This is probably a bug, would be good to open an issue if so.
> 

I'll file a bug for that. I think of using the screen shot as it is (after the updated font) for now. What do you think? Should we remove that section?


>     * Ensure all the photographs in the screenshots are licensed properly (e.g. the woman working in the paddy fields, and the ones in explore might have attribution requirements)

I've attributed the photo of the women working in the paddy field (it shows up on hovering over the corresponding image). Should we have to attribute those in the explore/search features too?

**Comment by sivaraam** [comment]
Just for the note, the page is still live at https://sivaraam.github.io/commons-app.github.io/

**Comment by domdomegg** [comment]
> > ```
> > * Investigate why the app bar text seems to have a load of padding to the left. In the search activity this is extreme, 'flowers' is practically centred! This is probably a bug, would be good to open an issue if so.
> > ```
> 
> I'll file a bug for that. For now, I think of using the screen shot as it is (after the updated font) for now. What do you think? Should we remove that section?

Keep it for now. We can always take more screenshots when this is resolved.

> > ```
> > * Ensure all the photographs in the screenshots are licensed properly (e.g. the woman working in the paddy fields, and the ones in explore might have attribution requirements)
> > ```
> 
> I've attributed the photo of the women working in the paddy field (it shows up on hovering over the corresponding image). Should we have to attribute those in the explore/search features too?

Yeah, we should attribute the others. Also it might be an idea to make the attribution more prominent, I don't know how though. Alternatively it might be good if we could find PD images so attribution is not necessary (but do keep the attribution in the alt attribute for good practice)

**Comment by sivaraam** [comment]
> (but do keep the attribution in the alt attribute for good practice)

Just for the sake of clarity, do you want me to include the attribution in the 'alt' attribute too? Currently, I've just mentioned in the 'title' attribute. Also, I'm not sure including it in the 'alt' makes sense as the text in it would be displayed only when it is **not possible to show** the corresponding image.

**Comment by domdomegg** [comment]
> Just for the sake of clarity, do you want me to include the attribution in the 'alt' attribute too? Currently, I've just mentioned in the 'title' attribute. Also, I'm not sure including it in the 'alt' makes sense as the text in it would be displayed only when it is **not possible to show** the corresponding image.

Whoops sorry, yeah I meant the title attribute.

**Comment by sivaraam** [comment]
I've attributed most of the images. Let me know if I've missed something and if there's anything else left here.

**Comment by sivaraam** [comment]
@domdomegg Thanks for reviewing! It was very useful :slightly_smiling_face:

**Pull request merged**
