### PR TITLE
Use a font stack to make the text look better

### PR DESCRIPTION
**Pull request by sivaraam**
The font stack has been borrowed from the recent font stack upgrade that
is being made to Wikipedia sites[1].

It looks a lot better that how it was before on the devices that have been
tested:

1. An Android phone
2. Firefox and Chrome on Ubuntu

This resolves an item in #28.

[1]: https://phabricator.wikimedia.org/T175877

### CODE REVIEW

**Comment by sivaraam** [comment]
The change could be seen live at https://sivaraam.gitlab.io/commons-app.github.io

**Comment by domdomegg** [comment]
Is this not already done by Bootstrap? Renders the same for me on your version (uses Roboto Light, which I expect as I'm on Linux and don't have other defaults installed).

https://getbootstrap.com/docs/4.1/content/reboot/#native-font-stack

**Comment by sivaraam** [comment]
> Is this not already done by Bootstrap? Renders the same for me on your version (uses Roboto Light, which I expect as I'm on Linux and don't have other defaults installed).
>

You are right about that. One difference I see in the font stack of bootstrap and the one that I've added is the 'Lato' font. I don't have the other defaults mentioned in the bootstrap reboot installed so it's defaulting to 'sans-serif' for me (which doesn't look very great). So, I was exploring about improving it (unaware of the native font stack of Bootstrap) and came to know about the Wikimedia font stack and used it. [As a result](https://sivaraam.gitlab.io/commons-app.github.io/) the site looked great (at least for me)! That's because of the Lato (which I have installed).

I'm including the screen shots just for the comparison.

**[Before PR](https://commons-app.github.io/)**
site-before-pr

**[After PR](https://sivaraam.gitlab.io/commons-app.github.io/)**
site-after-pr

Currently, I'm not sure about what to do here. I'm okay with either merging or closing this. Though I say this, I have a slight preference for using the Wikimedia font stack :wink:

**Comment by sivaraam** [comment]
> Ah okay, I think it makes sense to make it consistent with the Wikimedia font stack.

Thanks! I've just added a note about why we override the bootstrap's font-stack.

**Pull request merged**
