### PR TITLE
Added dark mode support

### PR DESCRIPTION
**Pull request by shinwookim**
Added dark mode support that:
- Pulls from user's device preference (using media queries)
- Save user preferences
- Simple toggle via Navbar

image

### CODE REVIEW

**Comment by sivaraam** [comment]
Thanks a lot for the PR! 

A few comments:

The shadow for the cards don't seem visible in dark mode. Could you look into possibility of tweaking them ?
image

Also, the toggle icon seems rather small. Would it be possible for you to use an icon that's easily noticeable. For example, the icons [used by Docusaurus](https://docusaurus.io/) seem good.

**Comment by shinwookim** [comment]
I've (hopefully) fixed the issue with the card shadows; and I've tried to modify the toggle buttons as well.

The color issue is a bit more tedious, since we are using a version of Bootstrap served from a CDN. The only thing I could think of is manually overriding all the classes with the new colors, but at that point, I think it would be better to bump bootstrap to 5.3 which supports dark mode colors natively.

**Comment by sivaraam** [comment]
> I think it would be better to bump bootstrap to 5.3 which supports dark mode colors natively (unless anyone has better suggestions, of course).

If the upgrade does not significantly affect the way the site is rendered, feel free to proceed with that way 👍🏼

**Comment by shinwookim** [comment]
Apologies for the late PR. 
Rather than attempting to bump Bootstrap (which broke a few things), I manually went in and modified the colors for the dark mode. 

Please review and let me know if I missed any colors.

**Comment by sivaraam** [comment]
Hey @shinwookim ! Thanks for the update. You changes are looking great on Firefox. Unfortunately, for some reason I don't see them reflecting on Chrome. See screenshot below:

image

Could you look into why that is the case ?

**Comment by sivaraam** [comment]
Looks great now. Thanks much for your contribution! 🙂

**Pull request merged**
