### PR TITLE
Revamp the steps for using the app

### PR DESCRIPTION
**Pull request by sivaraam**
The steps have become obsolete over updates and haven't been
updated for a long time.

Update them to reflect the current flow.

### CODE REVIEW

**Comment by sivaraam** [comment]
This change could be found live at https://sivaraam.github.io/commons-app.github.io/#usage

**Comment by domdomegg** [comment]
Can we remove "at this step" from the 6th step - I know it was there before but cutting it means each step fits on one line on the desktop site.

Also I think the 'next', 'next' and 'submit' steps can probably be cut to make it shorter, plus they are likely to change with the website become out of date again.

We also might want to have links to commons explaining naming policies, description guidelines, categorization and what the different licenses mean. I think links to commons would be better than us writing it out ourselves as it would remove the reduplication of effort and be more likely to be kept up to date.

**Comment by sivaraam** [comment]
> Can we remove "at this step" from the 6th step - I know it was there before but cutting it means each step fits on one line on the desktop site.
> 

That's just for the screen you saw the website on :wink: For the one I have, we would have to cut the "free at this step". But I'll remove it anyway as it seems to make the sentence too long.

Screenshot_2019-05-11 Commons Mobile App


> Also I think the 'next', 'next' and 'submit' steps can probably be cut to make it shorter, plus they are likely to change with the website become out of date again.
> 

That's right. May be we could make it a little more generic.

> We also might want to have links to commons explaining naming policies, description guidelines, categorization and what the different licenses mean. I think links to commons would be better than us writing it out ourselves as it would remove the reduplication of effort and be more likely to be kept up to date.

Links to commons would be good, of course. Some useful pages that I found:

* [First steps to Commons](https://commons.wikimedia.org/wiki/Commons:First_steps)
* [Licensing guide](https://commons.wikimedia.org/wiki/Commons:First_steps/License_selection)
* [Licensing policy](https://commons.wikimedia.org/wiki/Commons:First_steps/License_selection)
* [Categorization](https://commons.wikimedia.org/wiki/Commons:Categories#For_more_appropriate_categorization)
* [File naming](https://commons.wikimedia.org/wiki/Commons:File_naming)

**Comment by sivaraam** [comment]
@domdomegg We could add links to relevant policies and guides in another PR. Let me know if the changes are okay? For the note, I've re-phrased a sentence in Step 6 since you last approved the change.

**Comment by sivaraam** [comment]
> I'd probably remove the 'thens' in 8 and 9 but think that's just personal preference.

Not a strong preference :wink: Thanks for the quick review!

**Pull request merged**
