### PR TITLE
adding link of the main profile of the organisation in footer section

### LINKED ISSUE #46: Make a Footer for the website navigating to the organisations main github profile

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
## Description

I have given `btn` `btn-primary` classes to it which make it so cool. This will fixes #46 . Have a look at preview 👍🏻 

### Preview

test

@lopeselio have a look at this !! @nicolas-raoul Please review it ☺

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
So you mean the blue button design looks better?
Or do you mean that we need another link to GitHub?

**Comment by Vishal-raj-1** [comment]
> Or do you mean that we need another link to GitHub?

Yes, as mentioned in #46 .

**Comment by Vishal-raj-1** [comment]
May I close this PR?

**Comment by nicolas-raoul** [comment]
Yes thanks, sorry for the wasted work!
Before starting work on an issue, it is good to judge whether the issue has a consensus or not. When in doubt you can ask. Cheers!

**Comment by Vishal-raj-1** [comment]
> Yes thanks, sorry for the wasted work!
> Before starting work on an issue, it is good to judge whether the issue has a consensus or not. When in doubt you can ask. Cheers!

No Problem !! 😊 Cheers

**Pull request closed without merging**
