### PR TITLE
Adding documentation page

### LINKED ISSUE #4: Add documentation page
Cut-and-paste content from https://github.com/commons-app/apps-android-commons/wiki#user-documentation
That could include screenshots too :-)

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
# Description

Adding documentation and screenshots. It is responsive page. This will fixes #4 . Look at preview: 

### Preview
https://user-images.githubusercontent.com/59874304/104835368-2149f600-58cc-11eb-9bbd-25075fc7716e.mp4

@nicolas-raoul Sir Please review it !!

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
It looks great, thanks!

Would you mind making the sections linkable to?
For instance on the original page there is a small anchor for this:
Screen Shot 2021-01-17 at 18 31 22
It does not have to be an anchor icon, it could be something like `<h2><a id="fixing-errors-in-nearby"></a><a href="#fixing-errors-in-nearby">Fixing errors in Nearby</a></h2>` or similar?

**Comment by Vishal-raj-1** [comment]
> Would you mind making the sections linkable to?

Linkable to what? I guess you want to say `cursor:pointer;` for that.


>`<h2><a id="fixing-errors-in-nearby"></a><a href="#fixing-errors-in-nearby">Fixing errors in Nearby</a></h2>` or similar?

This doesn't works

**Comment by nicolas-raoul** [comment]
I sometimes need to point users to the right section. For instance let's say a user found an obsolete item and asks what to do. I would answer with this link: https://github.com/commons-app/commons-app-documentation/blob/master/android/How-to-install-and-use-the-app.md#obsolete-items

**Comment by Vishal-raj-1** [comment]
Is this good ?

https://user-images.githubusercontent.com/59874304/104846415-6720b180-5900-11eb-87bc-e14e8241d7f7.mp4

**Comment by nicolas-raoul** [comment]
Seems good! Can you please commit and push? Thanks!

**Comment by Vishal-raj-1** [comment]
> Seems good! Can you please commit and push? Thanks!

Sure !!

**Comment by Vishal-raj-1** [comment]
Squashing of commits is done !!

**Comment by nicolas-raoul** [comment]
Ah, would you mind:
- Inserting the same `<li class="nav-item"><a class="nav-link scroll" href="#docs">Documentation</a></li>` in index.html
- Making "Obsolete items" and "Wrong coordinates" into h3 rather than h2
? Thanks!

**Comment by Vishal-raj-1** [comment]
@nicolas-raoul Will do it today !!

**Pull request merged**
