### PR TITLE
Migrate to bootstrap

### PR DESCRIPTION
**Pull request by domdomegg**
See issue #20. Using bootstrap should make the site faster, easier to maintain and potentially look cleaner.

I've tried to keep it as close to the original one as possible. The main changes are the lack of a darker background behind the features pane and the footer being turned into more of a section of its own.

Before:
screencapture-commons-app-github-io-1484864367081
After:
screencapture-86-168-136-12-8887-1484864358384

### CODE REVIEW

**Comment by tobias47n9e** [comment]
This looks great. I just want to ask @nicolas-raoul  and @misaochan if they have privacy concerns about the usage of CDNs. If so it would be better to include the libraries locally.

**Comment by misaochan** [comment]
Hi guys, thanks for all the work being put into the website! :) I'm personally not too experienced in website development, but from what I've read about CDNs, lots of major websites use them without significant privacy concerns? Could you please elaborate on the concerns about privacy @tobias47n9e ?

**Comment by tobias47n9e** [comment]
If we use a CDN the website will request data from bootstrap, cloudflare and jquery. It is https but I don't know if WMF affiliated projects should ping so many 3rd parties?

See also:
http://security.stackexchange.com/questions/7843/what-are-the-risks-of-using-a-cdn-to-speed-up-my-website-how-do-i-avoid-them

**Comment by domdomegg** [comment]
IMO it's fine, bootstrap is widely used and as such will probably be pre-cached, reducing load time and strain on our servers + it being pre-cached means the user doesn't actually need to send a request to bootstrap/cloudflare/jquery except about once a year. [Source](http://stackoverflow.com/questions/10133816/script-cdn-usage-privacy-and-costs)

However, it would be easy to serve the bootstrap css files if really necessary.

**Comment by misaochan** [comment]
I see, thanks. If @nicolas-raoul doesn't have a strong opinion on this, I could ask on wikitech-l.

Are there any significant downsides to including the libraries locally instead?

**Comment by domdomegg** [comment]
Also, have a look at Wikimedia.org's own blog:

capture

**Comment by tobias47n9e** [comment]
@domdomegg That probably means there is no strong policy against using CDNs. In this case I will merge and we can always debate more later.

**Pull request merged**
