### PR TITLE
Updated - Navigation Bar Styling, animation, highlights active section and page smooth scrolling etc.

### PR DESCRIPTION
**Pull request by 0xpulsar**
**Features added:**
- Automatically update links in a navigation list based on scroll position.
- Favicon Added: Wikimedia Commons logo added as favicon.
- Smooth scrolling Added: On clicking on the navigation links, it scrolls smoothly to the section.
- Navigation bar: 
-- Styling and Coloring.
-- Animation of active link.

### CODE REVIEW

**Comment by sivaraam** [comment]
Hi @0xpulsar,

Just saw the live website. The changes seems to be nice. But the favicon doesn't seem to have come into effect. I still see no icon in the tab for the website. Any idea why?

**Comment by 0xpulsar** [comment]
Let me check.

**Comment by sivaraam** [comment]
> Can you fix it?

Just to be sure, fix **what**? Fix the missing website icon?

**Comment by sivaraam** [comment]
Anyways, I guess I've found the issue. I made a PR to your repo with the fix. https://github.com/0xpulsar/commons-app.github.io/pull/1

You could see it live at https://sivaraam.github.io/commons-app.github.io/

**Comment by 0xpulsar** [comment]
@sivaraam, I have merged it and solved merge conflict. can you review it?.

**Comment by sivaraam** [comment]
@0xpulsar On a cursory view, I guess the merge isn't proper. You seem to be including styles from both bootstrap 4.0.0-alpha and 4.1.1 as a consequence of which the page looks odd at some places. Could you re-merge it properly?

**Comment by sivaraam** [comment]
Closing this as #34 has been merged. Also, the website icon has been added in #38.

Hope to see you again @0xpulsar with another PR :)

**Pull request closed without merging**
